base: set locale to C.UTF-8
because en_US locale is not actually available in the container base
image

   >>> locale.setlocale(locale.LC_ALL, "C.UTF-8")
   'C.UTF-8'
   >>> locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/usr/lib64/python3.9/locale.py", line 610, in setlocale
       return _setlocale(category, locale)
   locale.Error: unsupported locale setting

related: https://github.com/rebase-helper/rebase-helper/issues/867

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>