[worker] Run probes only if not using AWS SQS
SQS does not support broadcast [1] and
running celery status/inspect results in
Error: Broadcast not supported by transport 'sqs'

[1] https://docs.celeryproject.org/en/latest/getting-started/brokers/index.html#broker-overview